### ISSUE TITLE
CVE-2022-37434 & CVE-2022-0778 reported on kube-proxy container

### ISSUE THREAD

**Issue by shnigam2** [kubernetes/kube-proxy#21]
WIZ reported CVE-2022-37434 & CVE-2022-0778 on kube-proxy container. Please let us know how can we remediate it..

Kube-proxy image which we are using -- registry.k8s.io/kube-proxy:v1.24.10

**Comment by danwinship** [comment]
sorry, belatedly noticing this. We don't use this repo for bug reports; they should be filed against kubernetes/kubernetes instead.

I suspect maybe this has already been addressed since you filed it, but if not, you can file a bug against k/k. (However, 1.24 is a year old now. While it is still getting updates, you may want to consider upgrading to a more recent version.)
